<?php
// $Id$

/**
 * @file
 *
 */


/*
 * Implements hook_backup_migrate_profiles().
 */
function incubator_us_backup_backup_migrate_profiles() {

  $out = array();
  $out['us_incubator_rsync_profile'] = backup_migrate_crud_create_item('profile', array (
    'profile_id' => 'us_incubator_rsync_profile',
    'name' => 'Rsync',
    'filename' => '[site:url-brief]',
    'append_timestamp' => '0',
    'timestamp_format' => 'Y-m-d\\TH-i-s',
    'filters' => 
    array (
      'compression' => 'gzip',
      'notify_success_enable' => 0,
      'notify_success_email' => '',
      'notify_failure_enable' => 0,
      'notify_failure_email' => '',
      'utils_site_offline' => 1,
      'utils_site_offline_message' => 'This site is currently under maintenance. We should be back shortly. Thank you for your patience.',
      'utils_description' => '',
      'destinations' => 
      array (
        'db' => 
        array (
          'exclude_tables' => 
          array (
          ),
          'nodata_tables' => 
          array (
            'cache' => 'cache',
            'cache_admin_menu' => 'cache_admin_menu',
            'cache_block' => 'cache_block',
            'cache_bootstrap' => 'cache_bootstrap',
            'cache_field' => 'cache_field',
            'cache_filter' => 'cache_filter',
            'cache_form' => 'cache_form',
            'cache_image' => 'cache_image',
            'cache_location' => 'cache_location',
            'cache_menu' => 'cache_menu',
            'cache_page' => 'cache_page',
            'cache_path' => 'cache_path',
            'cache_update' => 'cache_update',
            'cache_views' => 'cache_views',
            'cache_views_data' => 'cache_views_data',
            'search_dataset' => 'search_dataset',
            'search_index' => 'search_index',
            'search_total' => 'search_total',
            'sessions' => 'sessions',
          ),
          'utils_lock_tables' => 1,
          'use_mysqldump' => 0,
        ),
      ),
      'encryption' => 'none',
      'utils_disable_query_log' => true,
    ),
  ));
  
  return $out;
  
}

/*
 * Implements hook_backup_migrate_schedules().
 */
function incubator_us_backup_backup_migrate_schedules() {

  $out = array();
  $out['us_incubator_rsync_schedule'] = backup_migrate_crud_create_item('schedule',
    array (
      'schedule_id' => 'us_incubator_rsync_schedule',
      'name' => 'Rsync',
      'source_id' => 'db',
      'destination_id' => 'scheduled',
      'profile_id' => 'us_incubator_rsync_profile',
      'keep' => '1',
      'period' => '82800',
      'enabled' => '1',
      'cron' => '0',
    )
  );
  
  return $out;
};
